'use client';

// import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import styled from "styled-components";

// 字型載入
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 樣式定義
const Container = styled.div`
  display: flex; /* 確保容器使用 flex */
  overflow: hidden;
  padding: 0;
  margin: 0;
  height: 100vh;
  box-sizing: border-box;

  .left {
    flex: 1; /* 子項按照比例分配空間 */
    padding: 0;
    height: 100%;
    background-color: #f0f0f0;
  }

  .right {
    flex: 9;
    background: linear-gradient(to bottom,#fcce97, #C7802D);
    padding: 0px; 
    height: 100%;
    background-color: #fff;
    overflow-y: auto;

    &::-webkit-scrollbar {
      width: 5px;
    }
    &::-webkit-scrollbar-thumb {
      background-color: #888;
      border-radius:99px;
    }
    &::-webkit-scrollbar-track {
      background-color: #f1f1f1;
    }
  }
`;

// // Metadata
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Layout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StyledComponentsRegistry>
          <Container>
            <div className="left">left</div>
            <div className="right">{children}</div>
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
